### ISSUE TITLE
Replace "Load More" button with text

### ISSUE THREAD

**Issue by russmonk** [realitykeys/realitycheck#115]
When there are no questions in a category, we get a "Load More" button that is inactive. We should replace that with "No questions in this category yet" text.

![screen shot 2018-07-06 at 14 38 23](https://user-images.githubusercontent.com/19834038/42362521-aa8d539e-812e-11e8-9524-3cff5c839178.png)

**Comment by tokyoben** [comment]
Replaced with "scanning blockchain..." until the blockchain scan is complete, then if no questions displayed, "No questions in this category yet"
