### ISSUE TITLE
INT answers dont seem to be handled correctly

### ISSUE THREAD

**Issue by Overtorment** [realitykeys/realitycheck#91]
See question id 0x5b195850557779bf31cc40f8e757e93731fc0a486458b6f92ee3102051107360

"When will RealityCheck go live on MainNet? Answer in YYYYMMDD" 
Expects positive int.

When trying to answer 20171118 the answer is displayed as 0.000001801710193525
Cant even figure out how is this converted

**Comment by edmundedgar** [comment]
Thanks, we made a last-minute change on the way we handle decimals, so we probably broke something.

For dates in general, contracts would probably rather handle timestamps, so I've created this issue to create a question type that expects a date/time in the UI, then stores it as a unix timestamp.
https://github.com/realitykeys/realitycheck/issues/92

**Comment by edmundedgar** [comment]
OK, it was a dumb BN.js/BigNumber convertion bug, should be good now. Let me know if anything else misbehaves.

**Comment by Overtorment** [comment]
@edmundedgar can u reopen plz?
I see it being fixed for "Current answer", but for "History" it is atill broken

![image](https://user-images.githubusercontent.com/1913337/31492111-53a6e986-af52-11e7-97ce-f1887e8fa41d.png)

**Comment by edmundedgar** [comment]
Yes, the problem was with the way the answers were getting formatted before being sent to the contract, so the bug has left the bad data in the history. Answers submitted after it was fixed should be leaving correct data in the history.
