### ISSUE TITLE
unused parameters

### ISSUE THREAD

**Issue by rolandkofler** [realitykeys/realitycheck#97]
## Compilation warnings encountered:

realitycheck/truffle/contracts/Arbitrator.sol:45:28: Warning: Unused function parameter. Remove or comment out the variable name.
    function getDisputeFee(bytes32 question_id) constant returns (uint256) {
                           ^-----------------^
,realitycheck/truffle/contracts/ExplodingCallbackClient.sol:5:38: Warning: Unused function parameter. Remove or comment out the variable name.
    function __realitycheck_callback(bytes32 question_id, bytes32 question_answer) {
                                     ^-----------------^
,realitycheck/truffle/contracts/ExplodingCallbackClient.sol:5:59: Warning: Unused function parameter. Remove or comment out the variable name.
    function __realitycheck_callback(bytes32 question_id, bytes32 question_answer) {
                                                          ^---------------------^
,realitycheck/truffle/contracts/MetaQuestion.sol:84:13: Warning: Unused local variable.
            bool callback_result = caller.call.gas(callback_gas)(0x1d7dbb43, request_id, answer);
            ^------------------^

**Comment by edmundedgar** [comment]
Not sure if there's a best practice for this, the first 3 cases are there because someone might want to make a version that used the question_id, and the last one is there because Solidity also scolds you if you don't handle the return value from `call()`, although in this case we don't care what the response is (that's the responsibility of whoever paid for the thing to be called).

Guess we could log an event to shut it up, that might also be useful for test code.

**Comment by rolandkofler** [comment]
If extensibility is the motive it could be better to declare interfaces for the first 3 cases, then link dependencies against the interface instead of the implementation and using constructor injection to configure the system. Doing so the contract system would become more modular following the [open/closed principle](https://en.wikipedia.org/wiki/Open/closed_principle) which is a boon especially when investments in security audits should hold for a longer time. Certainly, the deployment configuration then is part of the audit. (A extremer view in the light of recent parity misconfiguration: recently someone at ConsesSys suggested that only deployed contracts should be audited)

**Comment by edmundedgar** [comment]
Makes sense, the idea is that Arbitrator.sol should be able to be substituted per-question (it's already a parameter when you make the question), so even if one arbitrator passes the audit you can't be sure that other questions will be using the same arbitrator contract. (For the same reason, we need to assume that the arbitrator contract may be hostile, so although they have to be trusted for the purposes of people interacting with a particular question, they shouldn't be able to do anything to harm affect other questions)

I suggest we also kick the whole meta-question / callback thing out of scope and just audit RealityCheck.sol and the other .sol files specifically imported in there. I'll edit the docs to remove references to MetaQuestions.

That makes the deployment configuration trivial (there are no constructor parameters) but deploying the contract before finalizing the audit and specifying the address of the audited contract sounds sensible anyhow. I'm out tomorrow but I should be able to deploy it on (my) Friday.

**Comment by edmundedgar** [comment]
Dammit, still syncing up a mainnet node, should be able to get it deployed tomorrow

**Comment by rolandkofler** [comment]
Nice, merry Christmas then 🐣

**Comment by edmundedgar** [comment]
OK, here it is, sorry for the delay.
https://etherscan.io/address/0x007112089f32c0fb6cc1921d4877c2c97270c5ab

Feel free to pick it up once you've had enough Christmas, have a great holiday...
